version: '3.8'
services:
  db:
    image: postgres:14-alpine # 使用 PostgreSQL 14 版本
    restart: always
    environment:
      - POSTGRES_USER=admin      # 设置数据库用户名
      - POSTGRES_PASSWORD=admin  # 设置数据库密码
      - POSTGRES_DB=what_to_wear # 设置数据库名称
    ports:
      - '5432:5432' # 将本机的5432端口映射到容器的5432端口
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
